version: "3.8"

services:
  nginx_proxy:
    image: nginx:stable-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/certbot:/etc/letsencrypt
      - ./proxy/www:/var/www/certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot_runner
    volumes:
      - ./proxy/certbot:/etc/letsencrypt
      - ./proxy/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
             certbot renew --webroot -w /var/www/certbot --quiet;
             sleep 12h;
             done"
